apiVersion: v2
name: ark-evaluator
description: >-
  Holistic Evaluator for Ark - AI-powered query evaluation service inc.
  LLM-as-a-Judge
type: application
version: 0.1.42
appVersion: 0.1.36
keywords:
  - evaluator
  - llm
  - ai
  - evaluation
  - llm-as-judge
maintainers:
  - name: Ark Team
sources:
  - https://github.com/mckinsey/agents-at-scale-ark
annotations:
  ark.mckinsey.com/service: ark-evaluator
  ark.mckinsey.com/resources: service
