{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: argo-minio-credentials
type: Opaque
stringData:
  accesskey: {{ .Values.minio.tenant.configSecret.accessKey }}
  secretkey: {{ .Values.minio.tenant.configSecret.secretKey }}
{{- end }}
